export const animals = ['Aardwolf',
  'Admiral',
  'Adouri',
  'African black crake',
  'African buffalo',
  'African bush squirrel',
  'African clawless otter',
  'African darter',
  'African elephant',
  'African fish eagle',
  'African ground squirrel',
  'African jacana',
  'African lion',
  'African lynx',
  'African pied wagtail',
  'African polecat',
  'African porcupine',
  'African red-eyed bulbul',
  'African skink',
  'African snake',
  'African wild cat',
  'African wild dog',
  'Agama lizard',
  'Agile wallaby',
  'Agouti',
  'Albatross',
  'Albatross',
  'Alligator',
  'Alligator',
  'Alpaca',
  'Amazon parrot',
  'American Virginia opossum',
  'American alligator',
  'American badger',
  'American beaver',
  'American bighorn sheep',
  'American bison',
  'American black bear',
  'American buffalo',
  'American crow',
  'American marten',
  'American racer',
  'American woodcock',
  'Anaconda',
  'Andean goose',
  'Ant',
  'Anteater',
  'Anteater',
  'Antechinus',
  'Antelope ground squirrel',
  'Antelope',
  'Antelope',
  'Antelope',
  'Arboral spiny rat',
  'Arctic fox',
  'Arctic ground squirrel',
  'Arctic hare',
  'Arctic lemming',
  'Arctic tern',
  'Argalis',
  'Armadillo',
  'Armadillo',
  'Armadillo',
  'Armadillo',
  'Asian elephant',
  'Asian false vampire bat',
  'Asian foreset tortoise',
  'Asian lion',
  'Asian openbill',
  'Asian red fox',
  'Asian water buffalo',
  'Asian water dragon',
  'Asiatic jackal',
  'Asiatic wild ass',
  'Ass',
  'Australian brush turkey',
  'Australian magpie',
  'Australian masked owl',
  'Australian pelican',
  'Australian sea lion',
  'Australian spiny anteater',
  'Avocet',
  'Azara\'s zorro',
  'Baboon',
  'Baboon',
  'Baboon',
  'Baboon',
  'Baboon',
  'Badger',
  'Badger',
  'Badger',
  'Badger',
  'Bahama pintail',
  'Bald eagle',
  'Baleen whale',
  'Banded mongoose',
  'Bandicoot',
  'Bandicoot',
  'Bandicoot',
  'Barasingha deer',
  'Barbet',
  'Barbet',
  'Barbet',
  'Bare-faced go away bird',
  'Barking gecko',
  'Barrows goldeneye',
  'Bat',
  'Bat',
  'Bat',
  'Bat-eared fox',
  'Bateleur eagle',
  'Bear',
  'Bear',
  'Bear',
  'Bear',
  'Bear',
  'Beaver',
  'Beaver',
  'Beaver',
  'Beaver',
  'Bee-eater',
  'Bee-eater',
  'Bee-eater',
  'Bee-eater',
  'Beisa oryx',
  'Bengal vulture',
  'Bennett\'s wallaby',
  'Bent-toed gecko',
  'Bettong',
  'Bird',
  'Bird',
  'Bird',
  'Bird',
  'Bird',
  'Bird',
  'Bird',
  'Bison',
  'Black and white colobus',
  'Black bear',
  'Black curlew',
  'Black kite',
  'Black rhinoceros',
  'Black spider monkey',
  'Black swan',
  'Black vulture',
  'Black-backed jackal',
  'Black-backed magpie',
  'Black-capped capuchin',
  'Black-capped chickadee',
  'Black-cheeked waxbill',
  'Black-collared barbet',
  'Black-crowned crane',
  'Black-crowned night heron',
  'Black-eyed bulbul',
  'Black-faced kangaroo',
  'Black-footed ferret',
  'Black-fronted bulbul',
  'Black-necked stork',
  'Black-tailed deer',
  'Black-tailed prairie dog',
  'Black-tailed tree creeper',
  'Black-throated butcher bird',
  'Black-throated cardinal',
  'Black-winged stilt',
  'Blackbird',
  'Blackbuck',
  'Blackish oystercatcher',
  'Blacksmith plover',
  'Bleeding heart monkey',
  'Blesbok',
  'Bleu',
  'Bleu',
  'Blue and gold macaw',
  'Blue and yellow macaw',
  'Blue catfish',
  'Blue crane',
  'Blue duck',
  'Blue fox',
  'Blue peacock',
  'Blue racer',
  'Blue shark',
  'Blue waxbill',
  'Blue wildebeest',
  'Blue-breasted cordon bleu',
  'Blue-faced booby',
  'Blue-footed booby',
  'Blue-tongued lizard',
  'Blue-tongued skink',
  'Boa',
  'Boa',
  'Boa',
  'Boa',
  'Boa',
  'Boar',
  'Boat-billed heron',
  'Bobcat',
  'Bohor reedbuck',
  'Bonnet macaque',
  'Bontebok',
  'Booby',
  'Booby',
  'Booby',
  'Bottle-nose dolphin',
  'Boubou',
  'Brazilian otter',
  'Brazilian tapir',
  'Brindled gnu',
  'Brocket',
  'Brocket',
  'Brolga crane',
  'Brown and yellow marshbird',
  'Brown antechinus',
  'Brown brocket',
  'Brown capuchin',
  'Brown hyena',
  'Brown lemur',
  'Brown pelican',
  'Brush-tailed bettong',
  'Brush-tailed phascogale',
  'Brush-tailed rat kangaroo',
  'Buffalo',
  'Buffalo',
  'Buffalo',
  'Buffalo',
  'Bulbul',
  'Bulbul',
  'Bulbul',
  'Bunting',
  'Burchell\'s gonolek',
  'Burmese black mountain tortoise',
  'Burmese brown mountain tortoise',
  'Burrowing owl',
  'Bush dog',
  'Bushbaby',
  'Bushbuck',
  'Bushpig',
  'Bustard',
  'Bustard',
  'Bustard',
  'Butterfly',
  'Butterfly',
  'Butterfly',
  'Buttermilk snake',
  'Caiman',
  'California sea lion',
  'Camel',
  'Campo flicker',
  'Canada goose',
  'Canadian river otter',
  'Cape Barren goose',
  'Cape clawless otter',
  'Cape cobra',
  'Cape fox',
  'Cape raven',
  'Cape starling',
  'Cape white-eye',
  'Cape wild cat',
  'Capuchin',
  'Capuchin',
  'Capuchin',
  'Capuchin',
  'Capybara',
  'Caracal',
  'Caracara',
  'Caracara',
  'Cardinal',
  'Cardinal',
  'Caribou',
  'Carmine bee-eater',
  'Carpet python',
  'Carpet snake',
  'Cat',
  'Cat',
  'Cat',
  'Cat',
  'Cat',
  'Cat',
  'Cat',
  'Cat',
  'Cat',
  'Cat',
  'Cat',
  'Cat',
  'Catfish',
  'Cattle egret',
  'Cereopsis goose',
  'Chacma baboon',
  'Chameleon',
  'Cheetah',
  'Chestnut weaver',
  'Chickadee',
  'Chilean flamingo',
  'Chimpanzee',
  'Chipmunk',
  'Chital',
  'Chuckwalla',
  'Civet',
  'Civet cat',
  'Civet',
  'Civet',
  'Clark\'s nutcracker',
  'Cliffchat',
  'Coatimundi',
  'Coatimundi',
  'Cobra',
  'Cobra',
  'Cobra',
  'Cockatoo',
  'Cockatoo',
  'Cockatoo',
  'Cockatoo',
  'Cockatoo',
  'Cockatoo',
  'Coke\'s hartebeest',
  'Collared lemming',
  'Collared lizard',
  'Collared peccary',
  'Colobus',
  'Colobus',
  'Colobus',
  'Columbian rainbow boa',
  'Comb duck',
  'Common boubou shrike',
  'Common brushtail possum',
  'Common dolphin',
  'Common duiker',
  'Common eland',
  'Common genet',
  'Common goldeneye',
  'Common green iguana',
  'Common grenadier',
  'Common langur',
  'Common long-nosed armadillo',
  'Common melba finch',
  'Common mynah',
  'Common nighthawk',
  'Common palm civet',
  'Common pheasant',
  'Common raccoon',
  'Common rhea',
  'Common ringtail',
  'Common seal',
  'Common shelduck',
  'Common turkey',
  'Common wallaroo',
  'Common waterbuck',
  'Common wolf',
  'Common wombat',
  'Common zebra',
  'Common zorro',
  'Constrictor',
  'Cook\'s tree boa',
  'Coot',
  'Coqui francolin',
  'Coqui partridge',
  'Corella',
  'Cormorant',
  'Cormorant',
  'Cormorant',
  'Cormorant',
  'Cormorant',
  'Cormorant',
  'Cormorant',
  'Cormorant',
  'Cormorant',
  'Cottonmouth',
  'Cougar',
  'Cow',
  'Coyote',
  'Crab',
  'Crab',
  'Crab',
  'Crab-eating fox',
  'Crab-eating raccoon',
  'Crake',
  'Crane',
  'Crane',
  'Crane',
  'Crane',
  'Crane',
  'Crane',
  'Crane',
  'Creeper',
  'Crested barbet',
  'Crested bunting',
  'Crested porcupine',
  'Crested screamer',
  'Crimson-breasted shrike',
  'Crocodile',
  'Crow',
  'Crow',
  'Crow',
  'Crown of thorns starfish',
  'Crowned eagle',
  'Crowned hawk-eagle',
  'Cuis',
  'Curlew',
  'Currasow',
  'Curve-billed thrasher',
  'Dabchick',
  'Dama wallaby',
  'Dark-winged trumpeter',
  'Darter',
  'Darwin ground finch',
  'Dassie',
  'Deer',
  'Deer',
  'Deer',
  'Deer',
  'Deer',
  'Deer',
  'Deer',
  'Deer',
  'Deer',
  'Defassa waterbuck',
  'Denham\'s bustard',
  'Desert kangaroo rat',
  'Desert spiny lizard',
  'Desert tortoise',
  'Devil',
  'Dik',
  'Dingo',
  'Dog',
  'Dog',
  'Dog',
  'Dog',
  'Dolphin',
  'Dolphin',
  'Dolphin',
  'Dove',
  'Dove',
  'Dove',
  'Dove',
  'Dove',
  'Dove',
  'Dove',
  'Dove',
  'Downy woodpecker',
  'Dragon',
  'Dragon',
  'Dragon',
  'Dragon',
  'Dragon',
  'Dragon',
  'Dragonfly',
  'Dromedary camel',
  'Drongo',
  'Duck',
  'Duck',
  'Duck',
  'Duck',
  'Duiker',
  'Duiker',
  'Dunnart',
  'Dusky gull',
  'Dusky rattlesnake',
  'Eagle owl',
  'Eagle',
  'Eagle',
  'Eagle',
  'Eagle',
  'Eagle',
  'Eagle',
  'Eagle',
  'Eagle',
  'Eagle',
  'Eastern boa constrictor',
  'Eastern box turtle',
  'Eastern cottontail rabbit',
  'Eastern diamondback rattlesnake',
  'Eastern dwarf mongoose',
  'Eastern fox squirrel',
  'Eastern grey kangaroo',
  'Eastern indigo snake',
  'Eastern quoll',
  'Eastern white pelican',
  'Echidna',
  'Egret',
  'Egret',
  'Egret',
  'Egyptian cobra',
  'Egyptian goose',
  'Egyptian viper',
  'Egyptian vulture',
  'Eland',
  'Elegant crested tinamou',
  'Elephant',
  'Elephant',
  'Eleven-banded armadillo',
  'Elk',
  'Emerald green tree boa',
  'Emerald-spotted wood dove',
  'Emu',
  'Eurasian badger',
  'Eurasian beaver',
  'Eurasian hoopoe',
  'Eurasian red squirrel',
  'Euro wallaby',
  'European badger',
  'European beaver',
  'European red squirrel',
  'European shelduck',
  'European spoonbill',
  'European stork',
  'European wild cat',
  'Fairy penguin',
  'Falcon',
  'Falcon',
  'Fat-tailed dunnart',
  'Feathertail glider',
  'Feral rock pigeon',
  'Ferret',
  'Ferruginous hawk',
  'Field flicker',
  'Finch',
  'Fisher',
  'Flamingo',
  'Flamingo',
  'Flamingo',
  'Flamingo',
  'Flicker',
  'Flicker',
  'Flightless cormorant',
  'Flycatcher',
  'Flying fox',
  'Fork-tailed drongo',
  'Four-horned antelope',
  'Four-spotted skimmer',
  'Four-striped grass mouse',
  'Fowl',
  'Fox',
  'Fox',
  'Fox',
  'Fox',
  'Fox',
  'Fox',
  'Fox',
  'Fox',
  'Fox',
  'Fox',
  'Fox',
  'Francolin',
  'Francolin',
  'Frilled dragon',
  'Frilled lizard',
  'Fringe-eared oryx',
  'Frog',
  'Frogmouth',
  'Galah',
  'Galapagos albatross',
  'Galapagos dove',
  'Galapagos hawk',
  'Galapagos mockingbird',
  'Galapagos penguin',
  'Galapagos sea lion',
  'Galapagos tortoise',
  'Gambel\'s quail',
  'Gaur',
  'Gazelle',
  'Gazelle',
  'Gazer',
  'Gecko',
  'Gecko',
  'Gecko',
  'Gecko',
  'Gecko',
  'Gelada baboon',
  'Gemsbok',
  'Genet',
  'Genet',
  'Genoveva',
  'Gerbil',
  'Gerenuk',
  'Giant anteater',
  'Giant armadillo',
  'Giant girdled lizard',
  'Giant heron',
  'Giant otter',
  'Gila monster',
  'Giraffe',
  'Glider',
  'Glider',
  'Glider',
  'Glossy ibis',
  'Glossy starling',
  'Gnu',
  'Goanna lizard',
  'Goat',
  'Godwit',
  'Golden brush-tailed possum',
  'Golden eagle',
  'Golden jackal',
  'Golden-mantled ground squirrel',
  'Goldeneye',
  'Goldeneye',
  'Goliath heron',
  'Gonolek',
  'Goose',
  'Goose',
  'Goose',
  'Goose',
  'Goose',
  'Goose',
  'Goose',
  'Goose',
  'Goose',
  'Gorilla',
  'Grant\'s gazelle',
  'Gray duiker',
  'Gray heron',
  'Gray langur',
  'Gray rhea',
  'Great cormorant',
  'Great egret',
  'Great horned owl',
  'Great kiskadee',
  'Great skua',
  'Great white pelican',
  'Greater adjutant stork',
  'Greater blue-eared starling',
  'Greater flamingo',
  'Greater kudu',
  'Greater rhea',
  'Greater roadrunner',
  'Greater sage grouse',
  'Grebe',
  'Green heron',
  'Green vine snake',
  'Green-backed heron',
  'Green-winged macaw',
  'Green-winged trumpeter',
  'Grenadier',
  'Grenadier',
  'Grey fox',
  'Grey heron',
  'Grey lourie',
  'Grey mouse lemur',
  'Grey phalarope',
  'Grey-footed squirrel',
  'Greylag goose',
  'Griffon vulture',
  'Grison',
  'Grizzly bear',
  'Ground legaan',
  'Ground monitor',
  'Groundhog',
  'Grouse',
  'Grouse',
  'Guanaco',
  'Guerza',
  'Gull',
  'Gull',
  'Gull',
  'Gull',
  'Gull',
  'Gull',
  'Gull',
  'Gull',
  'Gulls',
  'Hanuman langur',
  'Harbor seal',
  'Hare',
  'Hartebeest',
  'Hartebeest',
  'Hawk',
  'Hawk',
  'Hawk',
  'Hawk-eagle',
  'Hawk-headed parrot',
  'Hedgehog',
  'Helmeted guinea fowl',
  'Hen',
  'Heron',
  'Heron',
  'Heron',
  'Heron',
  'Heron',
  'Heron',
  'Heron',
  'Heron',
  'Heron',
  'Heron',
  'Heron',
  'Herring gull',
  'Hippopotamus',
  'Hoary marmot',
  'Hoffman\'s sloth',
  'Honey badger',
  'Hoopoe',
  'Hornbill',
  'Hornbill',
  'Hornbill',
  'Hornbill',
  'Horned lark',
  'Horned puffin',
  'Horned rattlesnake',
  'Hottentot teal',
  'House crow',
  'House sparrow',
  'Hudsonian godwit',
  'Hummingbird',
  'Huron',
  'Hyena',
  'Hyena',
  'Hyena',
  'Hyrax',
  'Ibex',
  'Ibis',
  'Ibis',
  'Ibis',
  'Iguana',
  'Iguana',
  'Iguana',
  'Impala',
  'Indian giant squirrel',
  'Indian jackal',
  'Indian leopard',
  'Indian mynah',
  'Indian peacock',
  'Indian porcupine',
  'Indian red admiral',
  'Indian star tortoise',
  'Indian tree pie',
  'Insect',
  'Jabiru stork',
  'Jacana',
  'Jackal',
  'Jackal',
  'Jackal',
  'Jackal',
  'Jackal',
  'Jackrabbit',
  'Jaeger',
  'Jaguar',
  'Jaguarundi',
  'Japanese macaque',
  'Javan gold-spotted mongoose',
  'Javanese cormorant',
  'Jungle cat',
  'Jungle kangaroo',
  'Kaffir cat',
  'Kafue flats lechwe',
  'Kalahari scrub robin',
  'Kangaroo',
  'Kangaroo',
  'Kangaroo',
  'Kangaroo',
  'Kangaroo',
  'Kangaroo',
  'Kelp gull',
  'Killer whale',
  'King cormorant',
  'King vulture',
  'Kingfisher',
  'Kingfisher',
  'Kingfisher',
  'Kinkajou',
  'Kirk\'s dik dik',
  'Kiskadee',
  'Kite',
  'Klipspringer',
  'Knob-nosed goose',
  'Koala',
  'Komodo dragon',
  'Kongoni',
  'Kookaburra',
  'Kori bustard',
  'Kudu',
  'Land iguana',
  'Langur',
  'Langur',
  'Langur',
  'Lappet-faced vulture',
  'Lapwing',
  'Lapwing',
  'Large cormorant',
  'Large-eared bushbaby',
  'Lark',
  'Laughing dove',
  'Laughing kookaburra',
  'Lava gull',
  'Leadbeateri\'s ground hornbill',
  'Least chipmunk',
  'Lechwe',
  'Legaan',
  'Legaan',
  'Legaan',
  'Lemming',
  'Lemming',
  'Lemur',
  'Lemur',
  'Lemur',
  'Lemur',
  'Lemur',
  'Leopard',
  'Leopard',
  'Lesser double-collared sunbird',
  'Lesser flamingo',
  'Lesser masked weaver',
  'Lesser mouse lemur',
  'Levaillant\'s barbet',
  'Lilac-breasted roller',
  'Lily trotter',
  'Lion',
  'Lion',
  'Lion',
  'Lion',
  'Lion',
  'Lion',
  'Lion',
  'Lion',
  'Lion',
  'Lion',
  'Little blue penguin',
  'Little brown bat',
  'Little brown dove',
  'Little cormorant',
  'Little grebe',
  'Little heron',
  'Lizard',
  'Lizard',
  'Lizard',
  'Lizard',
  'Lizard',
  'Lizard',
  'Lizard',
  'Lizard',
  'Llama',
  'Long-billed cockatoo',
  'Long-billed corella',
  'Long-crested hawk eagle',
  'Long-finned pilot whale',
  'Long-necked turtle',
  'Long-nosed bandicoot',
  'Long-tailed jaeger',
  'Long-tailed skua',
  'Long-tailed spotted cat',
  'Lorikeet',
  'Loris',
  'Lory',
  'Lourie',
  'Lynx',
  'Macaque',
  'Macaque',
  'Macaque',
  'Macaque',
  'Macaw',
  'Macaw',
  'Macaw',
  'Macaw',
  'Macaw',
  'Madagascar fruit bat',
  'Madagascar hawk owl',
  'Magellanic penguin',
  'Magistrate black colobus',
  'Magnificent frigate bird',
  'Magpie',
  'Magpie',
  'Malabar squirrel',
  'Malachite kingfisher',
  'Malagasy ground boa',
  'Malay squirrel',
  'Mallard',
  'Malleefowl',
  'Manatee',
  'Mandras tree shrew',
  'Mara',
  'Marabou stork',
  'Margay',
  'Marine iguana',
  'Marmot',
  'Marmot',
  'Marshbird',
  'Marten',
  'Masked booby',
  'Meerkat',
  'Meerkat',
  'Mexican beaded lizard',
  'Mexican boa',
  'Mexican wolf',
  'Miner\'s cat',
  'Mississippi alligator',
  'Moccasin',
  'Mocking cliffchat',
  'Mockingbird',
  'Mongoose',
  'Mongoose',
  'Mongoose',
  'Mongoose',
  'Mongoose',
  'Monitor lizard',
  'Monitor',
  'Monitor',
  'Monitor',
  'Monkey',
  'Monkey',
  'Monkey',
  'Monkey',
  'Monkey',
  'Monster',
  'Moorhen',
  'Moose',
  'Mouflon',
  'Mountain duck',
  'Mountain goat',
  'Mountain lion',
  'Mourning collared dove',
  'Mouse',
  'Mudskipper',
  'Mule deer',
  'Musk ox',
  'Mynah',
  'Mynah',
  'Native cat',
  'Nelson ground squirrel',
  'Neotropic cormorant',
  'Netted rock dragon',
  'Nighthawk',
  'Nile crocodile',
  'Nilgai',
  'Nine-banded armadillo',
  'North American beaver',
  'North American porcupine',
  'North American red fox',
  'North American river otter',
  'Northern elephant seal',
  'Northern fur seal',
  'Northern phalarope',
  'Nubian bee-eater',
  'Numbat',
  'Nutcracker',
  'Nuthatch',
  'Nyala',
  'Ocelot',
  'Old world fruit bat',
  'Olive baboon',
  'Onager',
  'Openbill stork',
  'Openbill',
  'Opossum',
  'Orca',
  'Oribi',
  'Oriental short-clawed otter',
  'Oriental white-backed vulture',
  'Ornate rock dragon',
  'Oryx',
  'Oryx',
  'Osprey',
  'Ostrich',
  'Otter',
  'Otter',
  'Otter',
  'Otter',
  'Otter',
  'Otter',
  'Otter',
  'Otter',
  'Ovenbird',
  'Owl',
  'Owl',
  'Owl',
  'Owl',
  'Owl',
  'Owl',
  'Ox',
  'Oystercatcher',
  'Paca',
  'Pacific gull',
  'Paddy heron',
  'Pademelon',
  'Painted stork',
  'Pale white-eye',
  'Pale-throated three-toed sloth',
  'Pallas\'s fish eagle',
  'Palm squirrel',
  'Pampa gray fox',
  'Paradoxure',
  'Parakeet',
  'Parrot',
  'Partridge',
  'Peacock',
  'Peacock',
  'Peccary',
  'Peccary',
  'Pelican',
  'Pelican',
  'Pelican',
  'Pelican',
  'Penguin',
  'Penguin',
  'Penguin',
  'Penguin',
  'Peregrine falcon',
  'Phalarope',
  'Phalarope',
  'Phalarope',
  'Phalarope',
  'Phascogale',
  'Phascogale',
  'Pheasant',
  'Pheasant',
  'Pie',
  'Pie',
  'Pied avocet',
  'Pied butcher bird',
  'Pied cormorant',
  'Pied crow',
  'Pied kingfisher',
  'Pig-tailed macaque',
  'Pigeon',
  'Pigeon',
  'Pine siskin',
  'Pine snake',
  'Pine squirrel',
  'Pintail',
  'Pintail',
  'Plains zebra',
  'Platypus',
  'Plover',
  'Plover',
  'Pocket gopher',
  'Polar bear',
  'Polecat',
  'Porcupine',
  'Porcupine',
  'Porcupine',
  'Porcupine',
  'Porcupine',
  'Porcupine',
  'Possum',
  'Possum',
  'Possum',
  'Possum',
  'Possum',
  'Potoroo',
  'Prairie falcon',
  'Praying mantis',
  'Prehensile-tailed porcupine',
  'Pronghorn',
  'Puffin',
  'Puku',
  'Puma',
  'Puma',
  'Puna ibis',
  'Purple grenadier',
  'Purple moorhen',
  'Pygmy possum',
  'Python',
  'Python',
  'Quail',
  'Quoll',
  'Quoll',
  'Rabbit',
  'Raccoon dog',
  'Raccoon',
  'Raccoon',
  'Racer snake',
  'Racer',
  'Racer',
  'Radiated tortoise',
  'Rainbow lory',
  'Rat',
  'Rat',
  'Rat',
  'Rattlesnake',
  'Rattlesnake',
  'Rattlesnake',
  'Raven',
  'Raven',
  'Red and blue macaw',
  'Red brocket',
  'Red deer',
  'Red hartebeest',
  'Red howler monkey',
  'Red kangaroo',
  'Red lava crab',
  'Red meerkat',
  'Red phalarope',
  'Red sheep',
  'Red squirrel',
  'Red-billed buffalo weaver',
  'Red-billed hornbill',
  'Red-billed toucan',
  'Red-billed tropic bird',
  'Red-breasted cockatoo',
  'Red-breasted nuthatch',
  'Red-capped cardinal',
  'Red-cheeked cordon bleu',
  'Red-headed woodpecker',
  'Red-knobbed coot',
  'Red-legged pademelon',
  'Red-necked phalarope',
  'Red-necked wallaby',
  'Red-shouldered glossy starling',
  'Red-tailed cockatoo',
  'Red-tailed hawk',
  'Red-tailed phascogale',
  'Red-tailed wambenger',
  'Red-winged blackbird',
  'Red-winged hawk',
  'Reedbuck',
  'Reindeer',
  'Rhea',
  'Rhea',
  'Rhea',
  'Rhesus macaque',
  'Rhesus monkey',
  'Rhinoceros',
  'Rhinoceros',
  'Rhinoceros',
  'Richardson\'s ground squirrel',
  'Ring dove',
  'Ring-necked pheasant',
  'Ring-tailed coatimundi',
  'Ring-tailed gecko',
  'Ring-tailed lemur',
  'Ring-tailed possum',
  'Ringtail',
  'Ringtail cat',
  'Ringtail',
  'River wallaby',
  'Roadrunner',
  'Roan antelope',
  'Robin',
  'Robin',
  'Rock dove',
  'Roe deer',
  'Roller',
  'Rose-ringed parakeet',
  'Roseat flamingo',
  'Roseate cockatoo',
  'Royal tern',
  'Rufous tree pie',
  'Rufous-collared sparrow',
  'Russian dragonfly',
  'Sable antelope',
  'Sacred ibis',
  'Saddle-billed stork',
  'Sage grouse',
  'Sage hen',
  'Sally lightfoot crab',
  'Salmon pink bird eater tarantula',
  'Salmon',
  'Sambar',
  'Sandgrouse',
  'Sandhill crane',
  'Sandpiper',
  'Sarus crane',
  'Savanna baboon',
  'Savanna fox',
  'Savannah deer',
  'Savannah deer',
  'Scaly-breasted lorikeet',
  'Scarlet macaw',
  'Scottish highland cow',
  'Screamer',
  'Screamer',
  'Sea birds',
  'Seal',
  'Seal',
  'Seal',
  'Seal',
  'Seal',
  'Secretary bird',
  'Serval',
  'Seven-banded armadillo',
  'Shark',
  'Sheathbill',
  'Sheep',
  'Sheep',
  'Sheep',
  'Shelduck',
  'Shelduck',
  'Short-beaked echidna',
  'Short-nosed bandicoot',
  'Shrew',
  'Shrike',
  'Shrike',
  'Shrike',
  'Sidewinder',
  'Sifaka',
  'Silver gull',
  'Silver-backed fox',
  'Silver-backed jackal',
  'Siskin',
  'Siskin',
  'Skimmer',
  'Skink',
  'Skink',
  'Skua',
  'Skua',
  'Skunk',
  'Skunk',
  'Slender loris',
  'Slender-billed cockatoo',
  'Sloth bear',
  'Sloth',
  'Sloth',
  'Sloth',
  'Sloth',
  'Small Indian mongoose',
  'Small-clawed otter',
  'Small-spotted genet',
  'Small-toothed palm civet',
  'Smith\'s bush squirrel',
  'Snake',
  'Snake',
  'Snake',
  'Snake',
  'Snake',
  'Snake',
  'Snake',
  'Snake',
  'Snake-necked turtle',
  'Snow goose',
  'Snowy egret',
  'Snowy owl',
  'Snowy sheathbill',
  'Sociable weaver',
  'Sockeye salmon',
  'South African hedgehog',
  'South American meadowlark',
  'South American puma',
  'South American sea lion',
  'Southern black-backed gull',
  'Southern boubou',
  'Southern brown bandicoot',
  'Southern elephant seal',
  'Southern ground hornbill',
  'Southern hairy-nosed wombat',
  'Southern lapwing',
  'Southern right whale',
  'Southern screamer',
  'Southern sea lion',
  'Southern tamandua',
  'Southern white-crowned shrike',
  'Sparrow',
  'Sparrow',
  'Spectacled caiman',
  'Spider',
  'Spoonbill',
  'Spoonbill',
  'Sportive lemur',
  'Spotted deer',
  'Spotted hyena',
  'Spotted wood sandpiper',
  'Spotted-tailed quoll',
  'Springbok',
  'Springbuck',
  'Springhare',
  'Spur-winged goose',
  'Spurfowl',
  'Square-lipped rhinoceros',
  'Squirrel glider',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Squirrel',
  'Stanley bustard',
  'Stanley crane',
  'Starfish',
  'Starling',
  'Starling',
  'Starling',
  'Starling',
  'Steenbok',
  'Steenbuck',
  'Steller sea lion',
  'Steller\'s sea lion',
  'Stick insect',
  'Stilt',
  'Stone sheep',
  'Stork',
  'Stork',
  'Stork',
  'Stork',
  'Stork',
  'Stork',
  'Stork',
  'Stork',
  'Stork',
  'Stork',
  'Stork',
  'Stork',
  'Striated heron',
  'Striped dolphin',
  'Striped hyena',
  'Striped skunk',
  'Sugar glider',
  'Sulfur-crested cockatoo',
  'Sun gazer',
  'Sunbird',
  'Sungazer',
  'Superb starling',
  'Suricate',
  'Swainson\'s francolin',
  'Swallow',
  'Swallow-tail gull',
  'Swamp deer',
  'Swan',
  'Swan',
  'Tailless tenrec',
  'Tamandua',
  'Tammar wallaby',
  'Tapir',
  'Tarantula',
  'Tarantula',
  'Tasmanian devil',
  'Tawny eagle',
  'Tawny frogmouth',
  'Tayra',
  'Teal',
  'Tenrec',
  'Tern',
  'Tern',
  'Tern',
  'Tern',
  'Thirteen-lined squirrel',
  'Thomson\'s gazelle',
  'Thrasher',
  'Three-banded plover',
  'Tiger',
  'Tiger cat',
  'Tiger snake',
  'Timber wolf',
  'Tinamou',
  'Toddy cat',
  'Tokay gecko',
  'Topi',
  'Tortoise',
  'Tortoise',
  'Tortoise',
  'Tortoise',
  'Tortoise',
  'Tortoise',
  'Tortoise',
  'Toucan',
  'Toucan',
  'Tree porcupine',
  'Tropical buckeye butterfly',
  'Trotter',
  'Trumpeter swan',
  'Trumpeter',
  'Trumpeter',
  'Tsessebe',
  'Turaco',
  'Turkey vulture',
  'Turkey',
  'Turkey',
  'Turkey',
  'Turtle',
  'Turtle',
  'Turtle',
  'Turtle',
  'Two-banded monitor',
  'Two-toed sloth',
  'Two-toed tree sloth',
  'Tyrant flycatcher',
  'Uinta ground squirrel',
  'Urial',
  'Verreaux\'s sifaka',
  'Vervet monkey',
  'Vicuna',
  'Vine snake',
  'Violet-crested turaco',
  'Violet-eared waxbill',
  'Viper',
  'Vulture',
  'Vulture',
  'Vulture',
  'Vulture',
  'Vulture',
  'Vulture',
  'Vulture',
  'Vulture',
  'Vulture',
  'Vulture',
  'Wagtail',
  'Wallaby',
  'Wallaby',
  'Wallaby',
  'Wallaby',
  'Wallaby',
  'Wallaby',
  'Wallaby',
  'Wallaby',
  'Wallaroo',
  'Wambenger',
  'Wapiti',
  'Warthog',
  'Water legaan',
  'Water moccasin',
  'Water monitor',
  'Waterbuck',
  'Waterbuck',
  'Wattled crane',
  'Waved albatross',
  'Waxbill',
  'Waxbill',
  'Waxbill',
  'Weaver',
  'Weaver',
  'Weaver',
  'Weaver',
  'Weaver',
  'Weeper capuchin',
  'Western bearded dragon',
  'Western grey kangaroo',
  'Western lowland gorilla',
  'Western palm tanager',
  'Western patch-nosed snake',
  'Western pygmy possum',
  'Western spotted skunk',
  'Whale',
  'Whale',
  'Whale',
  'Whale',
  'Whip-tailed wallaby',
  'White rhinoceros',
  'White spoonbill',
  'White stork',
  'White-bellied sea eagle',
  'White-browed owl',
  'White-browed sparrow weaver',
  'White-cheeked pintail',
  'White-eye',
  'White-eye',
  'White-faced tree rat',
  'White-faced whistling duck',
  'White-fronted bee-eater',
  'White-fronted capuchin',
  'White-headed vulture',
  'White-lipped peccary',
  'White-mantled colobus',
  'White-necked raven',
  'White-necked stork',
  'White-nosed coatimundi',
  'White-rumped vulture',
  'White-tailed deer',
  'White-tailed jackrabbit',
  'White-throated kingfisher',
  'White-throated monitor',
  'White-throated robin',
  'White-throated toucan',
  'White-winged black tern',
  'White-winged dove',
  'White-winged tern',
  'Wild boar',
  'Wild turkey',
  'Wild water buffalo',
  'Wildebeest',
  'Wolf spider',
  'Wolf',
  'Wolf',
  'Wolf',
  'Wombat',
  'Wombat',
  'Wood pigeon',
  'Woodchuck',
  'Woodcock',
  'Woodpecker',
  'Woodpecker',
  'Woodrat',
  'Woolly-necked stork',
  'Worm snake',
  'Woylie',
  'Yak',
  'Yellow baboon',
  'Yellow mongoose',
  'Yellow-bellied marmot',
  'Yellow-billed hornbill',
  'Yellow-billed stork',
  'Yellow-brown sungazer',
  'Yellow-crowned night heron',
  'Yellow-headed caracara',
  'Yellow-necked spurfowl',
  'Yellow-rumped siskin',
  'Yellow-throated sandgrouse',
  'Zebra',
  'Zebra',
  'Zorilla',
  'Zorro'];
